### ISSUE TITLE
Release 1.7.02

### ISSUE THREAD

**Issue by jaschultz** [jaschultz/testspace.getting-started#4]
Focus on new Feature `ABC`
```
testspace:
  branch: "main"
  specs:
    - path: "manual/hello.md"
```
